version: '3'

services:
    api:
        platform: linux/amd64
        build: .
        restart: always
        links:
            - postgis
            - ignite
        ports:
            - "8443:8443"
            - "8444:8444"
            - "8446:8446"
            - "8080:8080"

    ignite:
        platform: linux/amd64
        restart: always
        image: apacheignite/ignite:2.13.0

    postgis:
        platform: linux/amd64
        image: kartoza/postgis:13.0
        restart: 'always'
        ports:
            - 5433:5432
        environment:
            - ALLOW_IP_RANGE=0.0.0.0/0
            - POSTGRES_DB=cot
            - POSTGRES_USER=martiuser
            - POSTGRES_PASS=local123
            - POSTGRES_MULTIPLE_EXTENSIONS="postgis","uuid-ossp"
